<?php

declare(strict_types=1);

namespace JacyImp\CloudIpDetector;

enum Provider: string
{
    case A2Hosting = 'a2hosting';
    case Adyen = 'adyen';
    case Ahrefs = 'ahrefs';
    case Akamai = 'akamai';
    case Alibaba = 'alibaba';
    case ApplePrivateRelay = 'apple_private_relay';
    case ArubaCloud = 'aruba_cloud';
    case Atlassian = 'atlassian';
    case Aws = 'aws';
    case Backblaze = 'backblaze';
    case BingBot = 'bing_bot';
    case Branch = 'branch';
    case BunnyCdn = 'bunny_cdn';
    case BunnyMagicContainers = 'bunny_magic_containers';
    case Choopa = 'choopa';
    case CircleCi = 'circleci';
    case CiscoWebex = 'cisco_webex';
    case Cloudflare = 'cloudflare';
    case CysoCloud = 'cyso_cloud';
    case Datadog = 'datadog';
    case DigitalOcean = 'digital_ocean';
    case Dreamhost = 'dreamhost';
    case EquinixMetal = 'equinix_metal';
    case Exoscale = 'exoscale';
    case Fastly = 'fastly';
    case FlyIo = 'flyio';
    case GcoreCdn = 'gcore_cdn';
    case GcoreCloud = 'gcore_cloud';
    case Github = 'github';
    case Gitlab = 'gitlab';
    case Godaddy = 'godaddy';
    case GoogleBot = 'google_bot';
    case GoogleCloud = 'google_cloud';
    case GrafanaCloud = 'grafana_cloud';
    case Gridscale = 'gridscale';
    case HcpTerraform = 'hcp_terraform';
    case HerokuAws = 'heroku_aws';
    case Hetzner = 'hetzner';
    case HuaweiCloud = 'huawei_cloud';
    case Infomaniak = 'infomaniak';
    case Intercom = 'intercom';
    case IonosCloud = 'ionos_cloud';
    case Kamatera = 'kamatera';
    case Linode = 'linode';
    case MetaCrawler = 'meta_crawler';
    case Microsoft365 = 'microsoft_365';
    case MicrosoftAzure = 'microsoft_azure';
    case NewRelicSynthetics = 'new_relic_synthetics';
    case Nforce = 'nforce';
    case Okta = 'okta';
    case Onlinesas = 'onlinesas';
    case OpenAi = 'openai';
    case OpenTelekomCloud = 'open_telekom_cloud';
    case OracleCloud = 'oracle_cloud';
    case Ovh = 'ovh';
    case Pagerduty = 'pagerduty';
    case Perplexity = 'perplexity';
    case Rackspace = 'rackspace';
    case Render = 'render';
    case SalesforceHyperforce = 'salesforce_hyperforce';
    case Scaleway = 'scaleway';
    case Seeweb = 'seeweb';
    case Sentry = 'sentry';
    case SoftlayerIbm = 'softlayer_ibm';
    case Stripe = 'stripe';
    case Telegram = 'telegram';
    case Tencent = 'tencent';
    case Ucloud = 'ucloud';
    case Upcloud = 'upcloud';
    case Vercel = 'vercel';
    case Vultr = 'vultr';
    case Wasabi = 'wasabi';
    case Yandex = 'yandex';
    case YandexCloud = 'yandex_cloud';
    case Zendesk = 'zendesk';
    case Zscaler = 'zscaler';
}
